- name: Create dotfiles symbolic links
  file:
    src: "{{ playbook_dir }}/{{ item.name }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { name: .zshrc, dest: ~/.zshrc }
    - { name: .zshenv, dest: ~/.zshenv }
    - { name: .vimrc, dest: ~/.vimrc }
    - { name: .vimrc, dest: ~/.config/nvim/init.vim }
    - { name: .config/nvim/coc-settings.json, dest: ~/.config/nvim/coc-settings.json }
    - { name: .config/nvim/dein/plugins.toml, dest: ~/.config/nvim/dein/plugins.toml }
    - { name: .config/nvim/ftplugin/go.vim, dest: ~/.config/nvim/ftplugin/go.vim }
    - { name: .tmux.conf, dest: ~/.tmux.conf }

- name: Create ~/.config/dotfiles
  file:
    path: ~/.config/dotfiles
    state: directory
    recurse: yes
    mode: 0755

- name: Create zsh custom configuration file
  copy:
    content: ""
    dest: ~/.config/dotfiles/zsh-custom-conf.zsh
    force: no
    mode: 0755
