- name: Create dotfiles symbolic links
  file:
    src: "{{ playbook_dir }}/{{ item }}"
    dest: "~/{{ item }}"
    state: link
  loop:
    - .tmux.conf
    # TODO: neovim config file location
    - .vimrc
    - .zshenv
    - .zshrc