- block:
    - name: Install apt packages
      become: yes
      apt:
        pkg:
          - curl
          - gawk
          - zsh
        state: present
        update_cache: yes

    - name: Check login shell
      shell: grep -E "^$(whoami):" /etc/passwd | cut -d ":" -f 7
      register: login_shell

    - block:
        - name: Get current user
          shell: whoami
          register: whoami
        - name: Change login shell to zsh
          become: yes
          shell: chsh {{ whoami.stdout }} -s $(which zsh)
      when: login_shell.stdout.find("zsh") == -1

  when: ansible_os_family == 'Debian'

- name: Install brew packages
  homebrew:
    name:
      # The default shell on macOS is zsh
      - curl
      - gawk
    state: present
    update_homebrew: yes
  when: ansible_os_family == 'Darwin'


- name: Check zplug existence
  stat:
    path: ~/.zplug
  register: zplug

- block:
    - name: Download zplug installer
      get_url:
        url: https://raw.githubusercontent.com/zplug/installer/master/installer.zsh
        dest: /tmp/installer.zsh

    - name: Install zplug
      command: zsh /tmp/installer.zsh

  when: not zplug.stat.exists
