- name: Install zsh
  become: yes
  apt:
    name: zsh
    state: present
    update_cache: yes

- name: Check login shell
  shell: grep $(whoami) /etc/passwd | cut -d ":" -f 7
  register: login_shell

- block:
    - name: Get current user
      shell: whoami
      register: whoami
    - name: Change login shell to zsh
      become: yes
      shell: chsh {{ whoami.stdout }} -s $(which zsh)
  when: login_shell.stdout.find("zsh") == -1
