- name: Install zsh and zplug dependencies using apt
  become: yes
  apt:
    pkg:
      - gawk
      - zsh
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install zplug dependencies using brew
  community.general.homebrew:
    name:
      # The default shell on macOS is zsh
      - gawk
    state: present
    update_homebrew: yes
  when: ansible_os_family == "Darwin"

- block:
    - name: Check login shell
      shell: grep -E "^$(whoami):" /etc/passwd | cut -d ":" -f 7
      register: login_shell

    - name: Change login shell to zsh
      shell: chsh $(whoami) -s $(which zsh)
      when: login_shell.stdout.find("zsh") == -1

  when: ansible_os_family == "Debian"

- name: Check zplug existence
  stat:
    path: ~/.zplug
  register: zplug

- block:
    - name: Download zplug installer
      get_url:
        url: https://raw.githubusercontent.com/zplug/installer/master/installer.zsh
        dest: /tmp/zplug_installer.zsh

    - name: Install zplug
      command: zsh /tmp/zplug_installer.zsh

  when: not zplug.stat.exists

- name: Install starship theme using brew
  community.general.homebrew:
    name:
      - starship
    state: present
    update_homebrew: yes
  when: ansible_os_family == "Darwin"

# TODO: Install for Ubuntu
