- name: Install pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: ~/.pyenv
    update: no

- name: Install rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: ~/.rbenv
    update: no

- name: Check nvm existence
  stat:
    path: ~/.nvm
  register: nvm

- block:
    - name: Download nvm installer
      get_url:
        url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh
        dest: /tmp/nvm_installer.sh

    - name: Install nvm
      command: bash /tmp/nvm_installer.sh

  when: not nvm.stat.exists

# TODO: tmux
