- name: Install pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: ~/.pyenv
    update: no

- name: Install rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: ~/.rbenv
    update: no

- name: Install nvm
  debug:
    msg: Install nvm