name: macos

on:
  push:
    branches:
      - master
      - feature/*

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64
      - name: Prerequisites
        run: |
          pip install -r requirements.txt
          git clone https://github.com/sstephenson/bats.git && bats/install.sh /usr/local
      - name: Install
        run: |
          make install
