name: ci

on:
  push:
    branches:
      - master
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
      - uses: dschep/install-pipenv-action@v1
      - name: Install dependencies
        run: |
          pipenv install --dev
          pipenv shell
          ansible --version
      # - name: Setup NodeJs
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: "12.x"
      # - name: Info
      #   run: |
      #     echo "node: `node --version`"
      #     echo "npm:  v`npm --version`"
      #     echo "yarn: v`yarn --version`"
      #     git status
      # - name: Install Dependencies
      #   run: yarn
      # - name: Lint
      #   run: yarn lint
      # - name: Test
      #   run: yarn test
