name: ubuntu

on:
  push:
    branches:
      - master
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          # Hack to get setup-python to work on act
          if [ ! -f "/etc/lsb-release" ] ; then
            echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
          fi
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Prerequisites
        run: |
          apt -y update && apt -y install aptitude make python3-apt
          pip install -r requirements.txt
          git clone https://github.com/sstephenson/bats.git && sudo bats/install.sh /usr/local
      - name: Install
        run: |
          make install
      - name: Test
        run: |
          grep -E "^$(whoami):" /etc/passwd | cut -d ":" -f 7 | xargs basename
          make test