name: ci

on:
  push:
    branches:
      - master
      - feature/*

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [2.7, 3.6, 3.7, 3.8]
        exclude:
          - os: macos-latest
            python-version: 3.8
    steps:
      - uses: actions/checkout@v2
      - name: Install pipenv and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv --upgrade-strategy=only-if-needed
          pipenv install --dev
          pipenv run ansible --version
      # - name: Setup NodeJs
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: "12.x"
      # - name: Info
      #   run: |
      #     echo "node: `node --version`"
      #     echo "npm:  v`npm --version`"
      #     echo "yarn: v`yarn --version`"
      #     git status
      # - name: Install Dependencies
      #   run: yarn
      # - name: Lint
      #   run: yarn lint
      # - name: Test
      #   run: yarn test
