name: ubuntu

on:
  push:
    branches:
      - master
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          # Hack to get setup-python to work on act
          if [ ! -f "/etc/lsb-release" ] ; then
            echo "DISTRIB_RELEASE=18.04" > /etc/lsb-release
          fi
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Install dependencies
        run: |
          apt -y update && apt -y install aptitude python3-apt make
          pip install -r requirements.txt
      - name: Execute "make install"
        run: |
          make install